name: Deploy to main branch

on:
  push:
    branches:
      - blog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blog branch
        uses: actions/checkout@v2
        with:
          ref: blog

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 根据你的项目需求设置正确的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Delete existing main branch (if exists)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch --prune --tags origin
          git branch -D main || true  # 删除已有的 main 分支，忽略删除失败的情况
          git push origin --delete main || true  # 从远程仓库删除 main 分支，忽略删除失败的情况

      - name: Checkout main branch
        run: |
          git fetch origin main  # 拉取远程 main 分支的最新内容
          git checkout main || git checkout -b main

      - name: Copy built assets
        run: |
          cp -r assets/* .

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Deploy to main branch"
          git push origin main
