name: Deploy to GitHub Pages

on:
  push:
    branches:
      - blog  # 触发条件：当推送到名为 "blog" 的分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # 检出代码库
        uses: actions/checkout@v2
        with:
          ref: blog  # 检出 blog 分支的代码

      - name: Set up Ruby  # 设置 Ruby 环境（适用于 Jekyll）
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # 根据你的项目需求设置正确的 Ruby 版本

      - name: Install Bundler  # 安装 Bundler（适用于 Jekyll）
        run: gem install bundler

      - name: Install dependencies  # 安装 Jekyll 依赖
        run: bundle install

      - name: Build Jekyll site  # 构建 Jekyll 网站
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages  # 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Jekyll 构建后的站点文件夹路径
          publish_branch: gh-pages  # 部署到的 GitHub Pages 分支
          cname: your-custom-domain.com  # 可选：自定义域名，如果有的话
