name: 部署到 GitHub Pages

on:
  push:
    branches:
      - blog

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # 确保 GITHUB_TOKEN 具有所需的权限

    steps:
      - name: 检出 blog 分支
        uses: actions/checkout@v2
        with:
          ref: blog

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 安装依赖
        run: npm install

      - name: 构建项目
        run: npm run build

      - name: 部署到 GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: ./_site  # 根据你的 Jekyll 构建输出目录调整
          branch: gh-pages
